"""chat table

Revision ID: 571b201c4a4d
Revises: 6b63b41cada1
Create Date: 2026-08-12 20:46:09.401318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '571b201c4a4d'
down_revision: Union[str, Sequence[str], None] = '6b63b41cada1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('document_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'chat_messages', 'documents', ['document_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.drop_column('chat_messages', 'document_id')
    # ### end Alembic commands ###
