"""add token_usage and is_admin

Revision ID: 72cadb3c5dd0
Revises: 8f2a1c4d9b7e
Create Date: 2026-08-23 20:39:30.372599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72cadb3c5dd0'
down_revision: Union[str, Sequence[str], None] = '8f2a1c4d9b7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_usage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('chat_message_id', sa.UUID(), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chat_message_id'], ['chat_messages.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_usage_conversation_id'), 'token_usage', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_token_usage_created_at'), 'token_usage', ['created_at'], unique=False)
    op.create_index(op.f('ix_token_usage_user_id'), 'token_usage', ['user_id'], unique=False)
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    op.drop_index(op.f('ix_token_usage_user_id'), table_name='token_usage')
    op.drop_index(op.f('ix_token_usage_created_at'), table_name='token_usage')
    op.drop_index(op.f('ix_token_usage_conversation_id'), table_name='token_usage')
    op.drop_table('token_usage')
    # ### end Alembic commands ###
